main: fun.fifu.fifusky.FiFuSky
version: 2.33
name: FiFuSky
author: NekokeCore
api-version: 1.16
commands:
  s:
    description: "主命令"
    usage: 命令输入有误！ /s help [命令] 查看帮助
  fs-admin:
    description: "管理员命令"
    usage: 命令输入有误！ /fs-admin help [命令] 查看帮助
